@baseUrl = http://localhost:3000

### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "c",
  "password": "c"
}

> {%
  client.global.set("access_token", response.body.token);
%}

### Get historic reservations
GET {{baseUrl}}/reservations/userHistorics
Authorization: {{access_token}}

### Create Reservation
POST {{baseUrl}}/reservations/createReservation
Content-Type: application/json
Authorization: {{access_token}}

{
  "cart": [
    {
      "idBatch": 6,
      "receiptDate": "2025-03-31T10:00:00Z",
      "quantity": 100,
      "pricePerUnit": 12.5,
      "product": {
        "name": "Example Product",
        "description": "This is an example product.",
        "productType": {
          "libelle": "Example Product Type"
        },
        "unit": {
          "name": "Kilogram"
        }
      },
      "producer": {
        "honorific": "Mr.",
        "firstName": "John",
        "lastName": "Doe",
        "email": "john.doe@example.com",
        "password": "securepassword123",
        "phoneNumber": "+123456789",
        "role": "Producer",
        "address": {
          "street": "123 Main Street",
          "number": "456",
          "box": "A",
          "postalCode": 12345,
          "city": "Cityville",
          "country": {
            "name": "Example Country"
          }
        },
        "company": "Example Company"
      }
    }
  ],
  "date": "2025-04-18T14:30:00.000Z"
}

### get all reservation for a user
GET {{baseUrl}}/reservations/getReservationsUser
Authorization: {{access_token}}
